package DAO

import "gorm.io/gorm"

type CourseEvalAggr struct {
	gorm.Model
	CourseCode                  string  `gorm:"size:50"`
	NumberOfResponse            int     `gorm:"type:int"`           // Number of survey response
	ChallengeAndEngagementIndex float32 `gorm:"type:decimal(10,2)"` // CEI index generated by CE
	OverallRating               float32 `gorm:"type:decimal(10,2)"` // Mean of all question median
	HoursPerWeek                float32 `gorm:"type:decimal(10,2)"` // Question 28
	InstructorsContribution     float32 `gorm:"type:decimal(10,2)"` // Question 3
	TeachingEffectiveness       float32 `gorm:"type:decimal(10,2)"` // Question 4
	CourseOrganization          float32 `gorm:"type:decimal(10,2)"` // Question 5
	ClarityOfConceptExplanation float32 `gorm:"type:decimal(10,2)"` // Question 7
	AvailabilityOfExtraHelp     float32 `gorm:"type:decimal(10,2)"` // Question 15
	UsefulnessOfCourseContent   float32 `gorm:"type:decimal(10,2)"` // Question 19
	GradingTechniques           float32 `gorm:"type:decimal(10,2)"` // Question 20
	ReasonableAssignedWork      float32 `gorm:"type:decimal(10,2)"` // Question 21
}
